ALTER TABLE ai_picks ADD COLUMN IF NOT EXISTS fail_reason TEXT NULL;
ALTER TABLE ai_picks ADD COLUMN IF NOT EXISTS fail_reason_tags TEXT NULL;
ALTER TABLE ai_picks ADD COLUMN IF NOT EXISTS fail_notes TEXT NULL;
